# Generated by Django 6.1 on 2026-09-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_education_experience_recruiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='is_open_to_work',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
